### ISSUE TITLE
Consolidate all our lightweight react-dom efforts

### ISSUE THREAD

**Issue by prometheansacrifice** [jquense/react-dom-lite#1]
Quoting from the email earlier.

> I just realised we all have independently been working on creating a light weight version of react-dom. It would be great if we could consolidate all our work into a single library.
> What do you think? The obvious question is who would be the maintainer. We all can. We could put this under a separate organisation, to be fair to everyone's work. Depending on how much time and effort we can spend and our priorities I'm sure we can definitely work it out.
> I'm equally excited about the new reconciler API as you guys. Let me know your thoughts :)

Just for reference I'm jotting down everyone's repos here so that we can take a look at each others work.

Jason Quense @jquense : https://github.com/jquense/react-dom-lite
Jiyahi Hu @jiayihu : https://github.com/jiayihu/react-tiny-dom/ 
Manas Jayanth @prometheansacrifice: https://github.com/prometheansacrifice/react-dom-lite/

**Comment by jquense** [comment]
Hey :wave: that's for taking the initiative here, it's super late where I am so I'm off to bed but happy to chat more about this :)

**Comment by jiayihu** [comment]
That sounds really cool! And I also agree we could start from this repo. Mine (react-tiny-dom)[https://github.com/jiayihu/react-tiny-dom] is focused on helping understanding custom renderers, not to provide a light alternative to react-dom.

Unfortunately I'm a very busy period of my life but I'll try to help you whenever I can. If are available on some Slack or Discord we could chat more about it.

P.S. @prometheansacrifice my name is `Jiayi`, not `Jiyahi` and it's spelled almost as `Jay` in English :D

**Comment by prometheansacrifice** [comment]
@jiayihu Extremely sorry about that! I'll be careful next time :)

> Unfortunately I'm a very busy period of my life but I'll try to help you whenever I can. If are available on some Slack or Discord we could chat more about it

Sure. We'd love it if you drop by and help :)

**Comment by prometheansacrifice** [comment]
@jquense That leaves the two of us. Can you please take a look at my work on [react-dom-lite](https://github.com/prometheansacrifice/react-dom-lite/) (coincidentally the same name)? Lets think of ways to merge the two projects.

**Comment by jquense** [comment]
@prometheansacrifice would you be comfortable working in this repo? A quick look at yours suggests you probably have more of of the Reconciler API implemented (maybe hydration) and here is a maybe more organized and split out? 

I'll start another issue right now with a list of the things I see as needed for general parity with react-dom

**Comment by prometheansacrifice** [comment]
Closing this issue. Thank you everyone for prompt and positive replies. It's really great to see everyone joining hands and supporting a single effort :)
