### ISSUE TITLE
Long installation times because of electron

### ISSUE THREAD

**Issue by prometheansacrifice** [jquense/react-dom-lite#22]
I was installing RDL earlier as an rpm package when I realised we have `react-devtools`. This led to a really long installation time because of electron. Do we need it? I grepped and couldn’t find where it was used. It seems it was added in the initial commit  https://github.com/jquense/react-dom-lite/blame/master/package.json. We must have missed it earlier since we already had electron installed.

**Comment by jquense** [comment]
We don't need it, I think it's just an accident it's there at all
