### ISSUE TITLE
Tooling and workflow setup

### ISSUE THREAD

**Issue by prometheansacrifice** [jquense/react-dom-lite#3]
We could mimic react's setup as much as possible to reduce the onboarding time for new contributors. I, for one, am comfortable and infact tuned to upstream's standards. Any disagreements/suggestions can be discussed here.

Things we need in the workflow before we proceed with any new development

- [x] Tests
- [x] Prettier 
- [x] Linting
- [x] Flow
- [x] CI

Please let me know if I missed something.

**Comment by jquense** [comment]
I think my only point of contention would be including flow. I tend to think its a detriment to new users and adds _a lot_ of extra overheard to managing the project tooling. Flow upgrades can be time consuming, and there are often bugs. Not to mention bad type defs. I think the downsides can worth it in large projects but I tend to think it'll probably cause more headache than it's worth (which is been my experience using it on a few projects).

What do you think?

**Comment by gaearon** [comment]
I'd say it can be really valuable for the renderer/reconciler interface ("host config"). We will likely change it relatively often, and it's hard to keep up if you don't check against our types. (Which we should expose on npm btw.)

That said maybe it's not that useful. I dunno.

**Comment by jquense** [comment]
that's fair, if React is going to expose useful types I'm a bit more amenable to it at least on the boundaries. My main is only that flow incurs a reasonable cost for maintainers that may not be worth it.

**Comment by prometheansacrifice** [comment]
@jquense Flow has helped me catch great deal of bugs. It has streamlined my flow of thought when it comes to data (and it's type) through out the code. I vote that it enters our setup.

**Comment by gaearon** [comment]
For the record, the types I'm referring to are these ones:

https://github.com/facebook/react/blob/8ec146c38ee4f4c84b6ecf59f52de3371224e8bd/packages/react-reconciler/src/ReactFiberReconciler.js#L50-L274

You can already copy paste them (assuming you copy them at the time when your version of `react-reconciler` was released). We'd love to expose them, it's just a matter of somebody sending a PR to React to move them into a separate file and then ship it with the package.

**Comment by jquense** [comment]
i'm ok adding it minimally. Honestly tho I tend to contribute to projects using flow less frequently than others simply because it often takes to much time fiddling with types, editor support, etc. I don't have endless amounts of time for side stuff so getting caught up dealing with tooling isn't ideal. Just trying to honest about it :)

**Comment by gaearon** [comment]
Btw I haven't set up any editor support still. I just run it on command line.

Again, I don't feel strongly about it at all—but figuring out the changes between host config API versions can be annoying if you can't verify.

**Comment by jquense** [comment]
Well let's at least annotate the host config bits. Maybe there is a middle ground between nothing and type all the things :)
