### ISSUE TITLE
Automagic setup?

### ISSUE THREAD

**Issue by technion** [jquense/react-dom-lite#31]
Hi,

Thanks a tonne for this library, I feel it's exactly what we need.

I'm just wondering if there's a sane way to somehow have this replace react-dom globally? The problem I have is:

- Install the module
- Change my only ReactDOM import in accordance with your example
- Suddenly bundle size goes up

The reason for this took a while to track down, being that material-ui at some point imports react-dom. Are you aware of any way to shim third party libraries without sending a series of PRs and hoping they accept?

**Comment by jquense** [comment]
The best way to shim it would be to use your bundle to alias react-dom to RDL, if your using webpack that should be very straight forward

**Comment by technion** [comment]
Hi,

Thanks for that information. I gave it a go, just adding this to my config.

 `    alias: { "react-dom": "react-dom-lite" },`


Unfortunately mounting a Material UI <Button> seems to crash in that configuration.

The error:
`
ButtonBase.js:169 Uncaught TypeError: Cannot read property 'findDOMNode' of undefined
    at ButtonBase.componentDidMount (ButtonBase.js:169)
    at commitLifeCycles (react-reconciler.development.js:4556)
    at commitAllLifeCycles (react-reconciler.development.js:5732)
    at HTMLUnknownElement.callCallback (react-reconciler.development.js:1613)
    at Object.invokeGuardedCallbackDev (react-reconciler.development.js:1652)
    at invokeGuardedCallback (react-reconciler.development.js:1509)
    at commitRoot (react-reconciler.development.js:5836)
    at performWorkOnRoot (react-reconciler.development.js:6803)
    at performWork (react-reconciler.development.js:6753)
    at requestWork (react-reconciler.development.js:6664)
`

That call is here:

https://github.com/mui-org/material-ui/blob/v1.4.3/packages/material-ui/src/ButtonBase/ButtonBase.js#L104

 I have not been able to determine if this if react-dom-lite, an issue in the material-ui code (although this did work prior to the alias), or an issue with how I did the alias. Any assistance appreciated.

**Comment by prometheansacrifice** [comment]
The fix was added [here](https://github.com/jquense/react-dom-lite/commit/3a3ecc175ad1a6af06adfb4667c9a4b06668e21f). I guess , this was not pushed to npm. Would you like to push it @jquense ?

On a related note, we should start maintaining tag information here

**Comment by technion** [comment]
Thanks for identifying that.
I'm currently on 0.3.0 (latest according to npm). Would greatly appreciate a new release.

**Comment by jquense** [comment]
0.4.0 is out! let me know if that helps

**Comment by technion** [comment]
Thanks a tonne, 0.4.0 resolved my issues.
